apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sas-postgres
  labels:
    sas.com/monitoring-base: kube-viya-monitoring
spec:
  selector:
    matchLabels:
      name: sas-crunchy-data-postgres
  endpoints:
  - port: postgres-exporter
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_label_name]
      regex: .+
      targetLabel: exp_type
      replacement: pg
    - sourceLabels: [__meta_kubernetes_pod_label_sas_com_deployment]
      targetLabel: sas_deployment
