apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway
  labels:
    sas.com/monitoring-base: kube-viya-monitoring
spec:
  selector:
    matchLabels:
      app: prometheus-pushgateway
  endpoints:
  - port: http
