apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sas-cas-operator
  labels:
    sas.com/monitoring-base: kube-viya-monitoring
spec:
  selector:
    matchLabels:
      name: sas-cas-operator
  endpoints:
  - port: metrics
    path: /metrics
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_sas_com_deployment]
      targetLabel: sas_deployment
