prometheus:
  prometheusSpec:
    listenLocal: true
    alerting:
      alertmanagers:
      - apiVersion: v2
        name: prometheus-operator-alertmanager
        namespace: monitoring
        pathPrefix: /
        port: web
        scheme: https
        tlsConfig:
          insecureSkipVerify: true
    containers:
      # Add square/ghosttunnel TLS proxy
      - name: tls-proxy
        args:
        - server
        - --listen=:9490
        - --target=127.0.0.1:9090
        - --key=cert/key
        - --cert=cert/cert
        - --disable-authentication
        image: squareup/ghostunnel:v1.5.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9490 
          name: https
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cert
          name: tls-proxy-secret
          readOnly: true
    volumes:
      - name: tls-proxy-secret
        secret:
          defaultMode: 420
          secretName: prometheus-operator-admission
  service:
    port: 9490
    targetPort: 9490

# alertmanager:
#   alertmanagerSpec:
#     listenLocal: true
#     containers:
#       # Add square/ghosttunnel TLS proxy
#       - name: tls-proxy
#         args:
#         - server
#         - --listen=:9493
#         - --target=127.0.0.1:9093
#         - --key=cert/key
#         - --cert=cert/cert
#         - --disable-authentication
#         image: squareup/ghostunnel:v1.5.2
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 9493 
#           name: https
#           protocol: TCP
#         resources: {}
#         securityContext:
#           allowPrivilegeEscalation: false
#           readOnlyRootFilesystem: true
#         terminationMessagePath: /dev/termination-log
#         terminationMessagePolicy: File
#         volumeMounts:
#         - mountPath: /cert
#           name: tls-proxy-secret
#           readOnly: true
#     # Issue: https://github.com/helm/charts/issues/22939
#     # alertmanagerSpec in this chart does not support volumes
#     volumes:
#       - name: tls-proxy-secret
#         secret:
#           defaultMode: 420
#           secretName: prometheus-operator-admission
#   service:
#     port: 9493
#     targetPort: 9493

prometheus-node-exporter:
  extraArgs:
  - --web.config=/opt/node-exporter/node-exporter-web.yaml
  configmaps:
  - name: node-exporter-tls-web-config
    mountPath: /opt/node-exporter

# node-exporter helm chart does not yet support HTTPS
# node-exporter:
#   sidecarVolumeMount:
#   - name: tls-secret
#     mountPath: /cert
#     readOnly: true

grafana:
  readinessProbe:
    httpGet:
      scheme: HTTPS
  livenessProbe:
    httpGet:
      scheme: HTTPS      
  extraSecretMounts:
  - name: tls-proxy-secret
    defaultMode: 420
    secretName: prometheus-operator-admission
    mountPath: /cert
    readOnly: true
  sidecar:
    datasources:
      defaultDatasourceEnabled: false
  "grafana.ini":
    server:
      protocol: https
      cert_file: /cert/cert
      cert_key: /cert/key
