prometheus:
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    port: 443
    targetPort: 443
    nodePort: null
  # Define host-based ingress
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    enabled: true
    tls:
    - hosts:
      - prometheus.host.mycluster.example.com
      secretName: monitoring-prometheus-tls-secret
    hosts:
    - prometheus.host.mycluster.example.com
  prometheusSpec:
    externalUrl: https://prometheus.host.mycluster.example.com:19486

alertmanager:
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    nodePort: null
  # Define host-based ingress
  ingress:
    enabled: true
    hosts:
    - alertmanager.host.mycluster.example.com
  alertManagerSpec:
    externalUrl: https://alertmanager.host.mycluster.example.com:19486

grafana:
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    nodePort: null
  # Define host-based ingress
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    enabled: true
    tls:
    - hosts:
      - grafana.host.mycluster.example.com
      secretName: monitoring-grafana-tls-secret
    hosts:
    - grafana.host.mycluster.example.com
  "grafana.ini":
    server:
      root_url: https://grafana.host.mycluster.example.com:19486