prometheus:
  prometheusSpec:
    listenLocal: true
    containers:
      # Add square/ghosttunnel TLS proxy
      - name: tls-proxy
        args:
        - server
        - --listen=:443
        - --target=127.0.0.1:9090
        - --key=/cert/tls.key
        - --cert=/cert/tls.crt
        - --disable-authentication
        image: squareup/ghostunnel:v1.5.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: https
          containerPort: 443 
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cert
          name: tls-proxy-secret
          readOnly: true
    securityContext:
      runAsNonRoot: false
    volumes:
      - name: tls-proxy-secret
        secret:
          defaultMode: 420
          secretName: monitoring-prometheus-tls-secret

# alertmanager:
#   alertmanagerSpec:
#     listenLocal: true
#     containers:
#       # Add square/ghosttunnel TLS proxy
#       - name: tls-proxy
#         args:
#         - server
#         - --listen=:9493
#         - --target=127.0.0.1:9093
#         - --key=cert/key
#         - --cert=cert/cert
#         - --disable-authentication
#         image: squareup/ghostunnel:v1.5.2
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 9493 
#           name: https
#           protocol: TCP
#         resources: {}
#         securityContext:
#           allowPrivilegeEscalation: false
#           readOnlyRootFilesystem: true
#         terminationMessagePath: /dev/termination-log
#         terminationMessagePolicy: File
#         volumeMounts:
#         - mountPath: /cert
#           name: tls-proxy-secret
#           readOnly: true
#     # Issue: https://github.com/helm/charts/issues/22939
#     # alertmanagerSpec in this chart does not support volumes
#     volumes:
#       - name: tls-proxy-secret
#         secret:
#           defaultMode: 420
#           secretName: prometheus-operator-admission
#   service:
#     port: 9493
#     targetPort: 9493

prometheus-node-exporter:
  extraArgs:
  - --web.config=/opt/node-exporter/node-exporter-web.yaml
  configmaps:
  - name: node-exporter-tls-web-config
    mountPath: /opt/node-exporter

# node-exporter helm chart does not yet support HTTPS
# node-exporter:
#   sidecarVolumeMount:
#   - name: tls-secret
#     mountPath: /cert
#     readOnly: true

grafana:
  readinessProbe:
    httpGet:
      scheme: HTTPS
      port: 443
  livenessProbe:
    httpGet:
      scheme: HTTPS
      port: 443
  extraContainers: |
    # Add square/ghosttunnel TLS proxy
    - name: tls-proxy
      args:
      - server
      - --listen=:443
      - --target=127.0.0.1:3000
      - --key=/cert/tls.key
      - --cert=/cert/tls.crt
      - --disable-authentication
      image: squareup/ghostunnel:v1.5.2
      imagePullPolicy: IfNotPresent
      ports:
      - name: https
        containerPort: 443 
        protocol: TCP
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        privileged: true
        readOnlyRootFilesystem: true
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /cert
        name: tls-proxy-secret
        readOnly: true
  extraContainerVolumes:
  - name: tls-proxy-secret
    secret:
      defaultMode: 420
      secretName: monitoring-grafana-tls-secret
  service:
    port: 443
    targetPort: 443
  sidecar:
    datasources:
      defaultDatasourceEnabled: false
  "grafana.ini":
    server:
      # Bind to localhost so https (tls-proxy) is the only way in
      http_addr: 127.0.0.1
