apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kibana-tls-cert
spec:
  commonName: kibana
  dnsNames:
  - localhost
  - prometheus-operator-kibana
  issuerRef:
    kind: Issuer
    name: namespace-issuer
  secretName: kibana-tls-secret
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth